import { spotifyInstance } from "./axios"
export const getProfile = async () => {
    const res = await spotifyInstance.get("/me")
    return {
        name: res.data.display_name,
        email: res.data.email,
        id: res.data.id,
        images: res.data.images
    }
}
export const searchSpotify = async (q) => {
    let res = await spotifyInstance.get(`/search?type=artist,track&q=${q}&limit=7`)
    return res.data
}
export const getGenreSeeds = async () => {
    const res = await spotifyInstance.get("/recommendations/available-genre-seeds")
    console.log(res.data)
    return res.data
}
export const magicRecommendation = async (seed_artist, seed_tracks) => {
    const res = await spotifyInstance.get(`/recommendations?seed_artists=${seed_artist.join(",")}&seed_tracks=${seed_tracks.join(",")}`)
    return res.data
}
export const createMagicPlaylistAndSave = async (userid, uriArr) => {
    const res = await spotifyInstance.post(`/users/${userid}/playlists`, {
        name: "Magic playlist",
        description: "Magic playlist generated by Ved"
    })
    const playlist_id = res.data.id
    const res2 = await spotifyInstance.post(`/playlists/${playlist_id}/tracks`, {
        uris: uriArr,
    })
    return res2.data
}